name = "ModelingToolkitNeuralNets"
uuid = "f162e290-f571-43a6-83d9-22ecc16da15f"
authors = ["Sebastian Micluța-Câmpeanu <sebastian.mc95@proton.me> and contributors"]
version = "2.2.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Aqua = "0.8"
ComponentArrays = "0.15.28"
DifferentiationInterface = "0.6, 0.7"
ForwardDiff = "0.10.36, 1"
IntervalSets = "0.7.10"
JET = "0.8, 0.9, 0.10"
Lux = "1.14"
LuxCore = "1.2"
ModelingToolkit = "10"
ModelingToolkitStandardLibrary = "2.24"
OptimizationBase = "4.0.2"
OptimizationOptimisers = "0.3"
OrdinaryDiffEqVerner = "1.2"
Random = "1.10"
SafeTestsets = "0.1"
SciMLSensitivity = "7.72"
SciMLStructures = "1.1.0"
StableRNGs = "1"
Statistics = "1.10"
SymbolicIndexingInterface = "0.3.41"
Symbolics = "6.43"
Test = "1.10"
Zygote = "0.6.73, 0.7"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SciMLStructures = "53ae85a6-f571-4167-b2af-e1d143709226"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "JET", "Test", "OrdinaryDiffEqVerner", "DifferentiationInterface",
    "SciMLSensitivity", "Zygote", "ForwardDiff", "ModelingToolkitStandardLibrary",
    "OptimizationBase", "OptimizationOptimisers", "SafeTestsets", "SciMLStructures",
    "StableRNGs", "Statistics", "SymbolicIndexingInterface"]
