[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitNeuralNets = "f162e290-f571-43a6-83d9-22ecc16da15f"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SciMLStructures = "53ae85a6-f571-4167-b2af-e1d143709226"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
ModelingToolkitNeuralNets = {path = ".."}

[compat]
Documenter = "1.3"
Lux = "1"
ModelingToolkit = "10"
ModelingToolkitNeuralNets = "2"
ModelingToolkitStandardLibrary = "2.7"
Optimization = "4.0"
OptimizationOptimisers = "0.3"
Plots = "1"
SciMLStructures = "1.1.0"
StableRNGs = "1"
Statistics = "1"
SymbolicIndexingInterface = "0.3.15"
